### ISSUE TITLE
SPA Implementation over Angular >2

### ISSUE THREAD

**Issue by badre429** [joeaudette/cloudscribe#125]
Is the any possiblity to have implementation on the Angular >2

**Comment by joeaudette** [comment]
I'm not sure what your question is.

You can use cloudscribe core as the user backend for spa using our IdentityServer4 integration, best [example is in our starter kits repo](https://github.com/joeaudette/cloudscribe.StarterKits/tree/master/cloudscribe-idserver-nodb), it has a spa example implemented with polymer, we don't have an angular example yet. I wrote a polymer wrapper around the oidc-client.js, probably would want something similar for angular.

But I'm not sure that is what you are asking. The management UI we have is written as MVC, if you are asking for a rewrite as angular I have no immediate plans for that, maybe someday will write an api version so others can write a UI in whatever they want.

**Comment by badre429** [comment]
thank you 
for my questions its about (webapi + ui ) implentation on angular +aspnetcore webapi

**Comment by joeaudette** [comment]
do you have any interest in working on that yourself?

**Comment by calebcwells** [comment]
Hey Joe,

I've been spending a lot of time tinkering with .NET Core and Angular 2 together. I pulled down your simplecontent sample and like what I see. Did you have anything specific in mind when it comes to integrating Angular 2? I could be interested.

Thanks,
Caleb Wells

**Comment by joeaudette** [comment]
Hi Caleb,

[SimpleContent is in a separate repo](https://github.com/joeaudette/cloudscribe.SimpleContent), would be better in general to post there, on this thread the op was asking about spa mangement ui for cloudscribe core. But since the approach would be the same for either project I will go ahead and answer here.

In general the way to go about it would be very similar for both projects, basically we would need to implement api controllers and apis as an alternative to the mvc approach that we have now. I'm very interested in getting there myself but I have so many higher priorities that it just isn't feasible for me to focus on that work right now, but for anyone who would like to do the needed work or get the ball rolling, I can tell you how I would go about it.

I would make a new class libary for each ie cloudscribe.Core.Web.Api and/or cloudscribe.SimpleContent.Web.Api depending on which you want to work on. Probably that class library would need to reference the existing web class libraries as well as the models project. Hopefully the service classes would have everything needed already to make it possible to implement the needed api methods since there is corresponding logic for mvc already. I would work on the spa ui and the web api methods in tandem, ie make the ui and make the api methods you need as you go according to your vision for the ui. I'm not sold on angular myself, if I were doing the work I would probably try to use [webcomponentns](https://www.webcomponents.org/) and [ploymer](https://www.polymer-project.org) but obviously whoever does the work can decide for themselves how to build it. The api could be re-used I would think if anyone wants to make their own ui with some other framework. 

Once the api is mostly done then we could look at some refactoring of things out of the current mvc web library so if someone wants to use api they don't have to bring along the mvc controllers or vice versa in their dependencies.

Other thing to think about before doing any major work is [copyright and licensing](https://github.com/joeaudette/cloudscribe/blob/master/CONTRIBUTING.md), ultimately my goal is for these projects to become part of the .NET Foundation and to be able to transfer copyrights for the code to the foundation.

With all that out of the way if someone still wants to help then I would be happy to have the help and would be glad to answer questions and maybe help if you need any additional service methods to facilitate the api design or have questions along the way.

**Comment by nigel-dewar** [comment]
@badre429 hey mate, not sure how far you got with this. I'm in the process of knocking out an Angular 1.x sample which will include a cordova (Ionic 1) sample. 

but that is not likely what you want, you want ng v2 right. I will produce an Angular 2 version as well afterwards, next 2-3 weeks, which will include
Angular 2 embedded within cloudscribe MVC Page (will use webpack for build)
Angular 2 stand alone project (for those whom love Angular-cli)
Electron (using Angular 2) sample
And Ionic 2 sample.

The work Joe has done is epic, and I'm only in the beginning stages of understanding what he has built, but I do see the need for 'front-end' samples so folks can get started with Joes cloudscribe faster, as at end of day, Joe' vision as he states is to reduce all the repetition and assist making multi-tenant easy, well that is my understanding of his vision anyway.

Yell out if you need an Angular 2 sample still. And anyone else who might need a ReactJS sample, yell out and I'll see about producing one for ya.

Side note, I have thought about cloudscribe (IdentityServer4) use with NativeScript, but not sure best way to tackle this. Looking at the IdentityServer guys pages, there does often pop up questions on Mobile app usage, Android etc that the IDSvr guy are not in position (certainly dont have the time coz they are really busy) to address. Guess then its up the community to provide.

**Comment by joeaudette** [comment]
fyi, I moved the MVC controllers into separate projects/nugets so the rest of the web stuff could be re-used if someone wants to make api controllers for use with spa front end. This way apis ever do get built then it is possible to leave out the mvc controllers. It is possible that someday I will implement api controllers if no-one else does but I have other priorities for some time to come.

**Comment by nigel-dewar** [comment]
Hi Joe, Nice i will check it out.


Sent from Samsung Mobile


-------- Original message --------
From: Joe Audette
Date:16/06/2017 07:12 (GMT+10:00)
To: joeaudette/cloudscribe
Cc: nigel-dewar , Comment
Subject: Re: [joeaudette/cloudscribe] SPA Implementation over Angular >2 (#125)


fyi, I moved the MVC controllers into separate projects/nugets so the rest of the web stuff could be re-used if someone wants to make api controllers for use with spa front end. This way apis ever do get built then it is possible to leave out the mvc controllers. It is possible that someday I will implement api controllers if no-one else does but I have other priorities for some time to come.
