### ISSUE TITLE
Decoupling clouldscribe.Identity from cloudscribe.Core.Web 

### ISSUE THREAD

**Issue by mikeandersun** [joeaudette/cloudscribe#15]
`clouldscribe.Identity` used in `cloudscribe.Core.Web`. Is it possible to remove this dependency and assemble `cloudscribe.Identity` whitin `example.WebApp`? 
I had a try by adding a new project (e.g `cloudscribe.Accounts`) and move related controllers(`AccountController` and `ManageController` and related views) but some components like `RequestTimeZoneResolver` use it. 
Although shipping views and html assets may be a problem with Nuget packaging.

**Comment by joeaudette** [comment]
I often have a hard time understanding your questions and comments. I wish you would try harder to articulate more clearly so I could understand more easily. Seems like if I ponder what you wrote for a long time I start to think I can guess what you mean but I'm not sure. I would have responded to this question sooner if it was more clear to me.

In this case I think maybe what you are suggesting is to move things like RequestSiteResolver and RequestTimeZoneResolver out of Core.Web and into the Identity project which would make it possible to use it without having a dependency on Core.Web project. Maybe you want to implement your own controllers instead of using the ones provided in Core.Web.  If that is what you mean then I agree and will do that soon.

Shipping views and other content assets in nuget is a problem right now. Actually at the moment it is possible to package the files into the nuget package but nuget does not currently install them. I am fairly certain that this will be fixed in rc2 or in 1.0 so I don't expect this to be a problem later.

**Comment by mikeandersun** [comment]
Sorry about that. 
What i means is : `cloudscribe.Core.Web` is depend on `clouldscribe.Identity`.
In my opinion using `cloudscribe.Core.Web`  without `clouldscribe.Identity` is better . I don't want to use `clouldscribe.Identity` at all. I use IdentityServer3 for AuthN/AuthrZ.
My preferred is to use `cloudscribe.Core.Web` in my web app without  `clouldscribe.Identity`,but for now adding `cloudscribe.Core.Web` bring `clouldscribe.Identity` to my web app.
I think `clouldscribe.Identity` can be a webby project and move related controllers(AccountController and ManageController ) from `cloudscribe.Core.Web` to it , or a new webby project (e.g `cloudscribe.Accounts`) that use `clouldscribe.Identity` for identity management.
Thanks a lot for time to understand my comments. :)

**Comment by joeaudette** [comment]
Thanks for clarifying, now I understand what you are saying.

My goal is that people will be able to meet these scenarios:

* People can use cloudscribe.Identity 
* People can use both cloudscribe.Identity and Identity server
* People can use IdentityServer without cloudscribe.Identity

I have not yet started working with IdentityServer but I hope to get to that soon, and once I learn how to integrate it and how the parts fit together it will be more clear to me how to organize the code to meet those 3 goals. Right now the first goal is met, I will work on the second goal hopefully soon, and once that is working I will figure out how best to decouple things so that the 3rd goal is possible.

You may be right that I need to move those controllers out of core.web, but I'm not sure because I will need some version of account and manage controllers in all cases. Maybe I will need a way to abstract around the Identity and IdentityServer bits in a way that they can be easily plugged in without any hard dependency.

**Comment by mikeandersun** [comment]
IdentityServer has a `IUserService`  interface that can be implement to communicate with an accounts management database. I did some work to implement that with  `clouldscribe.Identity`. But the work was hard to me because they don't support ASP.NET 5 and have their DI system. 
BTW, I think the best point to start is:

1) Setup a cloudscribe-based web application client to accounts management and user registration.
2) Implement `IUserService` with `clouldscribe.Identity` to connect to the accounts management client database.
3)Hosting IdentitySever in a cloudscribe-based web app is good idea to get some hosting features but it need to have 2 first.
Accounts management as a client for IdentityServer is a nice a simple approach and Dominick Baier recommened it. I think google have the same architecture(`account.google.com` as Identity server and `myaccount.google.com` for user that can manage his/her account.
But for now I need to interact from my cloudscribe-based web app with my hosted IdentityServer.This is my reason that I don't need to having  `clouldscribe.Identity` in my cloudscribe-based web app at all.
Thanks for attention.

**Comment by mikeandersun** [comment]
Just like [cloudscribe.Web.SimpleAuth](https://github.com/joeaudette/cloudscribe.Web.SimpleAuth).
So we can choose one of them(cloudscribe.Web.SimpleAuth or cloudscribe.Core.Identity).

**Comment by joeaudette** [comment]
apps can use one or the other depending on their needs

cloudscribe.Web.SimpleAuth is for a very limited range of apps, ones that don't need multi tenancy or lots of users.

it is possible for someone to implement an app that could use either cloudscribe.Core or cloudscribe.Web.SimpleWebAuth

I am working on a blog app, that can work with cloudscribe.Web.SimpleAuth and it can store its posts as xml files, after I get it working, then I will make an adapter so it is also possible use cloudscribe.Core using EF for all data instead of xml files or json

for small sites I will use xml for posts and cloudscribe.Web.SimpleAuth so the whole app can run without a database.

for larger sites I will use cloudscribe.Core and EF for all data

but it will not likely ever be possible to use cloudscribe.Core and cloudscribe.SimpleAuth together, or at least I don't plan on working on that

**Comment by joeaudette** [comment]
note that I do plan to decouple the cookie middleware from cloudscribe.Identity
but all of cloudscribe core is built on Identity, ie UserManager, UserStore, etc
Identity is the user back end and you should be able to use it with either cookie or jwt auth
so I do need to de-couple the cookie auth into its own projects, I am waiting to do that until after the next release of ASP.NET Core

**Comment by mikeandersun** [comment]
I am waiting for your blog and what you will do after ASP.NET next release.
fyi, I am working on a flat file-base CMS with json files. I will use your blog app.
