### ISSUE TITLE
free-software-is-suffering-because-coders-dont-know-how-to-write-documentation

### ISSUE THREAD

**Issue by robertosistemas** [joeaudette/cloudscribe#177]
[write-documentation](https://thenextweb.com/dd/2017/06/02/free-software-is-suffering-because-coders-dont-know-how-to-write-documentation)

**Comment by joeaudette** [comment]
1. this is the third issue you have posted about documentation in my projects. I do not need you to keep reminding me.
2. I already told you I am working on it https://www.cloudscribe.com/docs
3. I already saw that article and the survey
4. Criticism is the easiest thing to create, good software is hard work, good documentation is hard work. It is easy for you to tell me what I should do.  Where is the open source software and documentation you have made and shared with the world?
5. I don't work for you, you don't pay me, my work will progress at my own pace and schedule.
6. Part of the reason my projects nugets are still mostly preview is because I have not finished documentation yet. It is a goal for me to have good documentation.

**Comment by r41lblast** [comment]
@joeaudette  thank you for this great project! @robertosistemas carry on making your repo tests @GH fella

**Comment by joeaudette** [comment]
Thanks @r41lblast !
Given that there is now substantial documentation (though still more in the works), I think I will go ahead and close this issue.
