### ISSUE TITLE
Login by Username not working

### ISSUE THREAD

**Issue by gregfig** [joeaudette/cloudscribe#186]
Hey Joe,

I'm not sure exactly when it changed, but as of 1.2.0-rc20170615 (of cloudscribe.Core.Web), the login functionality does not work when logging in by username.  When you try, you get username cannot be null for FindByNameAsync().  Obviously because I'm not passing an email,  even if you have UseEmailForLogin to false.  When I flip it to true, and pass email it works great.

Log:
```
Connection id "0HL5VH4VLL41B": An unhandled exception was thrown by the application.
System.ArgumentNullException: Value cannot be null.
Parameter name: userName
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByNameAsync(String userName)
   at cloudscribe.Core.Web.Components.AccountService.<TryLogin>d__8.MoveNext()
```

I "think" (not sure) it happened when cloudscribe.Core.Web.Mvc was implemented.

(FYI, on the whole, Cloudscribe has been working great for my needs... nice work!)

Thanks.

**Comment by joeaudette** [comment]
Hi Greg,

Thanks for the bug report. I was able to reproduce and fix the problem. I have published new nugets and verified that it works with both email and username login in the starterkits with the updated nugets.
Just need to run the command dotnet restore --no-cache to make sure you get the latest nugets.

Thanks for your kind words. My guess is the problem was introduced when I refactored stuff out of the account controller into AccountService, the fix was needed in AccountService. That change was about the same time and in support of moving the controllers into cloudscribe.Core.Web.Mvc.
