### ISSUE TITLE
Tenant = site, project or blog?

### ISSUE THREAD

**Issue by CrispinF** [joeaudette/cloudscribe#218]
Hi Joe, a question really...
I've been looking around the cloudscribe tables in advance of starting a new project (to decide how to associate business-specific records with their "site" in a multi-tenant scenario) and seeing that the following fields all seem to be the same (though there are no FK relationships):
cs_ContentProject.Id
cs_Page.ProjectId
cs_Post.BlogId
cs_PostCategory.ProjectId
cs_PostComment.ProjectId
cs_Role.SiteId
cs_Site.Id (this being the primary)
cs_SiteHost.SiteId
cs_User.SiteId
cs_UserClaim.SiteId
cs_UserLocation.SiteId
I was a little confused by this, and to establish that these were really the same I had to look at content in a real database behind a site that had pages and blog posts etc.
So it seems that a "site", "project" and "blog" are now synonymous in cloudscribe? Is that correct? If so, might it be worth settling on one name to avoid future confusion?

And back to my original question, if we add custom tables to the database, within which records need to know which tenant they belong to, would you recommend naming it SiteId or ProjectId?

Related question - I had been expecting a table like cs_Blog that would give blog settings and link a blog to a site/project, but the above suggests you have firmly settled on one-blog-per-site - correct?

**Comment by joeaudette** [comment]
@CrispinF I'll start with your questions. In your custom tables you can use whatever column name you like but SiteId is what I would use. As noted in the Adding your own custom features section of the [main cloudscribe  core doc](https://www.cloudscribe.com/docs/cloudscribe-core) you can take a constructor dependency on SiteContext wherever you need it and the current site tenant will be injected so you have access to its id to tag your data with. Similarly you can depend on IUserContextResolver which can get you the current user from the db and you can use userid if needed to tag data in your custom feature. You definitely should not try to use foreign keys from your custom tables to cloudscribe tables, but indexes on siteid and userid in your data are a good idea since you will query on them.

The table you expected to be cs_Blog is actually cs_ProjectSettings.

Stuff about tables and naming are implementation details that most people don't need to worry about, and if they do they can figure it out or ask. cloudscribe brand spans a lot of projects that are all loosely coupled and evolved separately. You figured it out so it isn't that difficult, but I will explain some of the reasons for how things are named.
In particular cloudscribe SimpleContent and cloudscribe Core are completely independent projects with integration libraries that glue them together.
SimpleContent started life as only a blog based largely on MiniBlog. MiniBlog had file system storage with xml files which I evolved into a more generic solution NoDb which can store json but supports custom serialization so I was able to keep using the MiniBlog xml format for posts to make migration easier from other platforms but pages are stored as json. MiniBlog also had a very basic configuration based authentication system which I evolved into cloudscribe.SimpleAuth. I implemented multi tenancy in SimpleContent by having posts and pages attached to a project well before I integrated it with cloudscribe Core. That is how projectid came to be used for NoDb to keep the data separate per tenant/project, so projectid is like connection string for NoDb storage, because it is used as a folder name to isolate project/tenant files from each other. All of that was done before I even began work to integrate cloudscribe Core or to support database storage. So NoDb can be and is used now well beyond SimpleContent or my own projects, and some people also use cloudscribe.SimpleAuth independently. When it came time to implement integration with cloudscribe Core it was an obvious choice to map siteid as projectid to handle multitenany and siteid also becomes projectid in cs_ProjectSettings. That is just an implementation detail about the integration.

Both cloudscribe Core and SimpleContent were designed to be NoSql/DcoumentDb friendly and even when I implement storage in a relational database I don't feel compelled to adopt concepts like foreign key which is very specific to relational database platforms and is over-rated in my opinion. I don't use cascade deletes since I want to be NoSql friendly application logic should delete related data when needed rather than depending on foreign keys and cascade delete. Also there are lots of scenarios in application design where orphan rows are preferable to deleting all related data. If a user is deleted do I really want to delete any pages or blog posts for which he is the author? Going beyond existing functionality, would deleting previous orders be a good idea if a user account is deleted or a product? There are lots of cases where I would say no, and I don't cling to relational concepts that say yes. In the future I hope to also support MongDb and DcoumentDb which also won't support foreign keys. Just as we have loosely coupled libraries we also have loosely coupled data, we relate them with keys but we don't need the formality and rigidness of foreign keys.

**Comment by joeaudette** [comment]
@CrispinF if that answers your questions satisfactorily please close this issue otherwise feel free to ask additional or clarifying questions

**Comment by joeaudette** [comment]
The one inconsistency I wish was different is the cs_Posts uses blogid, if I were re-doing that I would use ProjectId there to be consistent, but blog came first so it got named that way and changing it now would be painful so not planning to. When I added pages support it seemed weird to tag pages with blogid hence what was originally BlogSettings became ProjectSettings to be more generic as a bucket of settings related to both

**Comment by CrispinF** [comment]
@joeaudette thanks for the explanations of current naming and where they came from. And as you kindly observed... "You figured it out so it isn't that difficult";-)   I agree with your comments above about cascade deletes btw - slavishly following RDBMS conventions can cause all sorts of problems in real world systems. 

One outstanding question about blog-site relationship... you said "The table you expected to be cs_Blog is actually cs_ProjectSettings" - we don't have that table in the BPS project https://github.com/exeGesIS-SDM/BritishPoultryScience which was started recently from one of your starter kits, but we have cs_ContentProject which seems to contain the blog behaviour settings - are we out of sync? Or, if you meant "cs_ContentProject", is it correct you have settled on one-blog-per-site as a design fundamental? (I'm gradually thinking through whether we like that or not for future projects, but in the past have found multiple blogs per site very powerful for unstructured repeating content).

**Comment by joeaudette** [comment]
@CrispinF 

yep my bad writing from memory, the table is cs_ContentProject

Regarding 1 project/blog per tenant, you are not limited to that. I chose that for the default integration with cloudscribe core but via customization it can be implemented differently.

In the library cloudscribe.Core.SimpleContent I implemented a custom [IProjectSettingsResolver](https://github.com/joeaudette/cloudscribe.SimpleContent/blob/master/src/cloudscribe.SimpleContent.Models/IProjectSettingsResolver.cs) named [SiteProjectSettingsResolver](https://github.com/joeaudette/cloudscribe.SimpleContent/blob/master/src/cloudscribe.Core.SimpleContent/SiteProjectSettingsResolver.cs). It looks in storage for one with a proejctid equal to the siteid, if not found it creates one and returns that. That was the easiest most straight forward way I could think of to integrate and cover the most common scenario.

But as with any interface/implementation combination you can replace that easily with another implementation via dependency injection. So by [taking over routing](https://www.cloudscribe.com/docs/custom-blog-routing) and project resolving with a custom IProjectSettingsResolver any scheme could be implemented and multiple projects/blogs/ could be implemented within a single tenant and resolving the project settings based on an url fragment added via custom routing most likely, but by any means you can think of.

**Comment by joeaudette** [comment]
Another way to have multiple blogs that actually should work today is to use the cloudscribe core multi-tenancy feature to represent the blogs, since we already have implemented by default a one to one correspondence between sites and projects/blogs. By using RelatedSitesMode=true in the mutli tenancy settings of cloudscribe core then any child tenants share the same users and roles as the master site, and using folder based tenants the folder can represent the root folder of the blog.

Using RelatedSitesMode with folder tenants it doesn't really act like different sites, authentication is shared so the folders only really correspond to different content roots/different projects in SimpleContent

**Comment by CrispinF** [comment]
@joeaudette thanks for those answers and possibilities. I think that's everything for now so I'll close this.
