### ISSUE TITLE
It is possible to create Local Package for projects?

### ISSUE THREAD

**Issue by mikeandersun** [joeaudette/cloudscribe#22]
I copy cloudscribe projects to my `src` folder of my project then add those to my solution.It causes my solutions with many projects and be slow. It is possible to create Local Nuget package for projects so that we can add cloudscribe Nuget packages locally?
Thanks

**Comment by joeaudette** [comment]
Eventually every project in the solution will be available as nuget packages, but there are several reasons why I'm not ready to publish more nugets yet.

At the moment I'm planning to split things up even more so it is going to get worse before it gets better because there will be even more projects.

Of course it is possible for you to make your own nugets, doing a build in release mode should create them under artifacts/bin. You can copy the nuget packages to a local folder and add that folder as a nuget source in visual studio. But my advice would be to wait a little longer because after I split things up into more projects, some of the smaller projects will be stable enough for me to publish nugets.

**Comment by mikeandersun** [comment]
I like your approach and waiting impatiently. :+1:
