### ISSUE TITLE
New NuGet packages

### ISSUE THREAD

**Issue by bdominguez** [joeaudette/cloudscribe#222]
Hi,

Why are you only targeting .NET Standard on new nuget releases? I want to also target .NET Standard but third party libraries don't allow me so I'm using ASP NET Core targeting .NET 4.6.2.

Now I can't update to the newest package version.

**Comment by joeaudette** [comment]
as far as I understand by targeting netstandard 1.6 it should work on desktop framework 4.6.1 or 4.6.2
https://github.com/dotnet/standard/blob/master/docs/versions.md
so by only targeting netstandard I've only dropped support for desktop framework 4.6.0 and lower

**Comment by joeaudette** [comment]
hmm, looking at this maybe I did break it for net 4.6.2 with netstandard1.6
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

but I have preview packages already for netstandard2.0 and that should work on desktop 4.6.1
asp/net core 2/0 and .net core 2.0 will ship very soon, all new development for cloudscribe is happening on the netcore2.0 branch which will become the master branch once 2.0 comes out of preview
not much difference in the latest 1.x cloudscribe packages so mean time I suggest pin to a specific version that works and then when 2.0 ships update your projects to 2.0. 

really what prompted me to drop back to only netstandard is because I'm trying to get these projects into the .net foundation and one of the requirements was to setup CI ie appveyor and travis, and those other targets I had before made it fail to build on linux/mac using travis so it simplified things for me
