### ISSUE TITLE
This may give some ideas. 

### ISSUE THREAD

**Issue by mikeandersun** [joeaudette/cloudscribe#24]
http://spring.io/projects

**Comment by joeaudette** [comment]
for casual comments or questions, please leave a message in the chat room instead of creating an issue.

[![Join the chat at https://gitter.im/joeaudette/cloudscribe](https://badges.gitter.im/joeaudette/cloudscribe.svg)](https://gitter.im/joeaudette/cloudscribe?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
