### ISSUE TITLE
Multi-Tenant question for Spa Applications

### ISSUE THREAD

**Issue by chispaK** [joeaudette/cloudscribe#298]
Goo day Joe,

I am in the early phases of doing a multi-tenant implementation using identity server 4 as an authentication service and Angular 2 as the SPA. 

I am looking at the great work you have done as an inspiration and would like to ask about resolving a SPA client:

Looking at your implementation it's not very clear how you resolve the SPA clients CachingSiteResolver as the hostname is always the name of the site hosting identity server in your sample sourceDev.WebApp when the resolver executes. Am missing something here? I am using the Polymer client samples you provided.

Should I be using the referer to resolve the SPA client in this case?

Thanks for this awesome repo.

**Comment by joeaudette** [comment]
@chispaK I hope you are working with the sample from here: https://github.com/joeaudette/cloudscribe.Samples/tree/master/cloudscribe-idserver-nodb
rather than working with the source code in this repository

As far as multi tenancy we have implemented multi tenancy for the identityserver back end, ie additional tenants have completely different users, clients, apis etc. The multi-tenancy can be configured either based on host names or on the first folder segment as documented here:https://www.cloudscribe.com/docs/multi-tenant-support
Note that with folder tenants the first tenant must be a root level tenant, and additional tenants must have a folder segment.

If a client application is in the same web site you would not even need identityserver because cookie auth would suffice. IdentityServer would be mainly for remote clients in other web applications.

The client must use the correct url for the identityserver tenant that is governing it. ie in my sample the Tenant2SpaPolymer client is specifiying the url for the second tenant in the attributes in the [index.html](https://github.com/joeaudette/cloudscribe.Samples/blob/master/cloudscribe-idserver-nodb/Tenant2SpaPolymer/wwwroot/index.html) like this:

    <my-app authority="http://localhost:50405/two"
            client-id="polymerclient2"
            scopes="openid profile tenant2Spa" 
            redirect-uri="http://localhost:5011/index.html?action=popupcallback"
            silent-redirect-uri="http://localhost:5011/silent-renew.html"
            post-logout-redirect-uri="http://localhost:5011/"
            sample-api-uri="http://localhost:5011/api/identity"></my-app>

Notice the folder segment "two" in the authority url because the sample is using folder based mutli-tenancy, if it were host name based then it would just use the host name.

The Tenant1SpaPolymer client is configured in it's [index.html](https://github.com/joeaudette/cloudscribe.Samples/blob/master/cloudscribe-idserver-nodb/Tenant1SpaPolymer/wwwroot/index.html) like this, without any url segment because it uses the root tenant as its authority:

    <my-app authority="http://localhost:50405"
            client-id="polymerclient"
            scopes="openid profile tenant1Spa" 
            redirect-uri="http://localhost:5010/index.html?action=popupcallback"
            silent-redirect-uri="http://localhost:5010/silent-renew.html"
            post-logout-redirect-uri="http://localhost:5010/"
            sample-api-uri="http://localhost:5010/api/identity"></my-app>

Note that I wrote a polymer wrapper around the [oidc-client.js](https://github.com/IdentityModel/oidc-client-js), I don't have one for angular but maybe someone else has written one if you search.

Hope that helps.

**Comment by joeaudette** [comment]
if that answers your question please close this issue.

**Comment by chispaK** [comment]
Good day Joe:

Sorry for slow response, just having a busy last 24hrs.

> if a client application is in the same website you would not even need identity server because cookie auth would suffice. IdentityServer would be mainly for remote clients in other web applications.

For my scenario, it's a single application that I want to be multi-tenanted using different hostnames. I am using identity service as my authentication service. From above do you mean identity server can be used for authorizing the different hostnames without additional configuration?

From your experience Joe, would you recommend the folder approach over the hostname approach or is this just a matter of preference.

Thanks for your speedy response.

**Comment by joeaudette** [comment]
yes IdentityServer4 with cloudscribe integration can be used for authorizing against multiple tenants based on host names.

The only advantage of the folder approach is ease of provisioning tenants because with folder tenants you just create new tenants from the cloudscribe UI and they work immediately. With host name tenants when you create new tenants from the cloudscribe UI the new tenants won't work until you configure the additional host name binding in IIS. As long as you are able to provision the dns host names and the host name bindings in IIS I would use different host names for each tenant rather than folders.

When you create a web with with the cloudscribe project template you get a dropdown for the mutli-tenant mode either FolderName, HostName, or None. If you created the project using FolderName but change your mind and want to use HostName, you can just update the MultiTenantOptions in appsettings.json changing the Mode from "FolderName" to "HostName"

**Comment by chispaK** [comment]
Thanks for the information Joe. I will now close this item
