### ISSUE TITLE
Use SQLite instead of LocalDB as the default for the dotnet-new template

### ISSUE THREAD

**Issue by Chaz6** [joeaudette/cloudscribe#311]
LocalDB is only supported on Windows, so please consider changing the default database to SQLite for the dotnet-new cloudscribe template.

**Comment by joeaudette** [comment]
we don't currently have support for SQLite at all. I could possibly make the default NoDb file system storage

**Comment by Chaz6** [comment]
I figured it out eventually, the default error was so long it went off the top off the terminal, and i realized i could change the db with an additional argument, so maybe it's not necessary after all. i don't know if it is possible to have some kind of warning message when using dotnet-new on non-windows platforms?

**Comment by joeaudette** [comment]
fyi I've implemented support for SQLite in all the cloudscribe projects and I've updated the command line project template on nuget to use SQLite as the default. I've also updated the Visual Studio project template but currently having problems trying to publish it in the VS Marketplace due to errors on their website.

**Comment by joeaudette** [comment]
I just now managed to update the Visual Studio extension, so now both project templates use SQLite by default.
