### ISSUE TITLE
Solution error when build

### ISSUE THREAD

**Issue by ITconsultants247** [joeaudette/cloudscribe#32]
This is a fix that I had to do in order to get the example.WebApp to run.  please advise if I have done something wrong.

I Just cloned the app to my machine and tried to rebuild the project.  I got an error on the following file:
 cloudscribe/src/cloudscribe.Core.Web/Navigation/ExtendedNavigationNode.cs
Line #23

The solution:
1.  I deleted the whole "Navigation" folder from cloudscribe.Core.Web
2.  I added the project cloudscribe.Web.Navigation to the solution
3.  modified the code in file: cloudscribe/src/example.WebApp/Startup.CloudscribeCore.DI.MS.cs
Line#261: services.TryAddScoped<INodeUrlPrefixProvider, FolderTenantNodeUrlPrefixProvider>(); 
To : services.TryAddScoped<INodeUrlPrefixProvider, DefaultNodeUrlPrefixProvider>();

only then, I was able to run the example Web App.

My changes were based on instinct and not experience.  please disregard if I don't make any sense.

**Comment by joeaudette** [comment]
Sorry about that and thanks for letting me know! if you revert that and get the latest it should build.

Problem was that I made some changes in cloudscribe.Web.Navigation project and published a new nuget but cloudscribe Core needs some changes to adapt to changes in the navigation project. I actually encountered this error and fixed it in the branch I'm working on but the master branch still had the problem.

basically, the project.json in example.WebApp and in cloudscribe.Core.Web had a reference to use the latest version of cloudscribe.Web.Navigation because the depedency was configured like this:

    "cloudscribe.Web.Navigation": "1.0.0-*"

for now I've changed it in the master branch to

    "cloudscribe.Web.Navigation": "1.0.0-beta7"

and now the master branch builds

once I complete the work I'm doing in a branch then I will be able to change it back to using the latest version of cloudscribe.Web.Navigation which is currently 1.0.0-beta8
