### ISSUE TITLE
DisplayName logic hardcoded.

### ISSUE THREAD

**Issue by MikeyUchiha** [joeaudette/cloudscribe#346]
Hi Joe,

I'm running into an issue where you've hardcoded the DisplayName logic here.

https://github.com/joeaudette/cloudscribe/blob/dfb27e2466a8396ad9788c93070a6e02ae478a3d/src/cloudscribe.Core.Identity/SiteUserManager.cs on Line 240

and

https://github.com/joeaudette/cloudscribe/blob/048554c7e78e24d16bc71a5b89e93e9b1bfd32c2/src/cloudscribe.Core.Web/Components/AccountService.cs on Line 77

I think that you should allow people to easily be able to customize this field. I should be able to add the field as a KVP or given the option to allow a new User to fill out their DisplayName, Also, if I want to, I should be able to easily override the logic for populating the DisplayName.

Thanks

**Comment by joeaudette** [comment]
Hi,

When a user registers via social auth we need something to populate that field and we don't have any other data available. Since those users don't go through the normal registration I don't think the user gets an opportunity to provide it. I can't remember off the top of my head if social registration forces users to provide the kvp required registration fields.

I think for normal registration you could use kvp custom registration to populate it just like you can for first/last name. And using kvp you should be able to make it editable by the user on the user profile. It is already editable by administrators in manage users.

I could potentially wrap an interface around that logic to let you override the behavior, but not sure what you could really do, what would you do differently, how would you populate it if I were to let you overrie it?

**Comment by joeaudette** [comment]
Looking at the kvp code I see that the list of native user properties doesn't include DisplayName making it not currently possible to make it editable by kvp custom props. I will definitely fix that and will also add an interface and default implementation so you can override the logic currently used.

**Comment by MikeyUchiha** [comment]
Joe,

I want the User’s DisplayName to use their Username. It would definitely be nice to allow it to be extendable. I don’t want Users to be able to edit it, I just want them to be able to see their Username on the upper right hand corner on login but others may want to allow the User be able to edit it.

It sounds like for External Login there needs to be a way to extend that form. When I wasn’t using Cloudscribe I had an extra form on the callback that required them to enter extra fields which looked just like the local registration form. Maybe you can add an extra KVP field that says “Editable in External Login Form” and have a checkbox that allows Cloudscribe users decide whether to use an extra External Login callback form for extra fields/validation. I will create another Issue to be able to handle this requirement.

Thanks!

**Comment by joeaudette** [comment]
Before filing a new issue first test to check whether social registrations are currently required to provide required kvp fields. It may already work, can't remember off the top of my head.

**Comment by joeaudette** [comment]
My view is that UserName is private data which is why we have separate DisplayName.
By default email and password is used to login but since email is often publicly known some people prefer to not use email for login and have a separate secret UserName. UserName must be unique per user and must be created at user creation time to a unique value, in case the setting is later changed from using email for login.

So if you are not using email for login you should treat username as private data and if you are using email for login then username is not something the user has to know about and it can be kept private in case you later change from using email.

DisplayName on the other hand does not have to be unique per user, is not meant to be private and  if you are going to let the user decide what to show as display name that is fine.

**Comment by MikeyUchiha** [comment]
Joe,

I agree with you in that the UserName should not be allowed to be edited by the User after registration. At the time of registration, I want the User's DisplayName to equal their Username and that's the requirement for my particular use case. I am using Username not email for login and that's why I would like to do it this way. Can you provide a way to override the logic for DisplayName so I can auto populate it with the UserName on registration?

Thanks

**Comment by joeaudette** [comment]
I have already published updated nugets for cloudscribe core this morning, you can inject a custom [INewUserDisplayNameReolver](https://github.com/joeaudette/cloudscribe/blob/master/src/cloudscribe.Core.Models/Identity/INewUserDisplayNameResolver.cs)

I am working on the kvp changes right now so that if you want users to be able to provide a displayname at registration time you will be able to.

**Comment by joeaudette** [comment]
I have published updated nuget for kvp that should support DisplayName. Just waiting for the package to get indexed and be available. Should be within the next hour.

**Comment by MikeyUchiha** [comment]
Thanks Joe.

How do I use this new DisplayNameResolver?

**Comment by joeaudette** [comment]
You don't use it directly, you implement the interface and inject it to replace the default implementation. SiteUser is passed in and you can return the UserName.
The default implementation uses the logic that was previously hard coded ie uses the email address substring. You could return the UserName. Whatever you return in your implementation is what the displayname will be set to.

**Comment by joeaudette** [comment]
ie 

    services.AddScoped<INewUserDisplayNameResolver, YourImplementation>();

**Comment by joeaudette** [comment]
alternatively implement DisplayName as a kvp custom registration property and let the user decide what to use.

**Comment by MikeyUchiha** [comment]
Understood! Thanks Joe
