### ISSUE TITLE
Roadmap and user management for multi-tenant apps

### ISSUE THREAD

**Issue by weedkiller** [joeaudette/cloudscribe#352]
Hi Joe, this is an awesome base, especially for multi tenant apps, users, menu/sitemap.

I wanted to share some things that would enhance cloudscribe, atleast make it easy to build up a community around you

1. Security: [NwebSec github](https://github.com/NWebsec/NWebsec)
2. User, Role & Tenant Management:
3. Auto-User Login: log every user attempt allows user Audits
4. [Datatables.net V2 and fully stable](https://github.com/ALMMa/datatables.aspnet)
5. How to build our own modules, are they plugins?
6. Marketplace for community to share modules
7. Scaffolding would be nice to scaffold an entity to CRUD datatable.
8. Payments
9. Boot strap 4
10. Auto-updates 

thanks

**Comment by MikeyUchiha** [comment]
2. Is already available by the way.

**Comment by joeaudette** [comment]
@weedkiller before I address the specific numbered items let  me provide a big picture.

cloudscribe is a set of library components for specific functionality, it is very customizable but it is not a framework and it is not shipped as an application. I ship only nugets and a project template that helps you generate an application with the libraries wired up. You own the application code and can make any changes to it you wish. I think some of these questions are because you perceive it as a framework and as an application. It is not a framework, it can be assembled into an application but is not shipped as an application because if it were then you would not be able to customize as easily. In asp.net core the main web application is the composition root where all things are configured and wired up and tied together, it is better for that to be fully under your control.

1. Since you own the application code nothing stops you from using that, just add it as needed in your startup.cs and/or program.cs. I "could" include options for that in our project template but I would rather not since then I am on the hook to provide support. I have enough open source code of my own to support. A community member could write a blog or tutorial for how to add that.

2. Already provided in cloudscribe Core

3. Currently login success and failure as well as registration success and failure are tracked in google analytics but not with and personal account data. We could potentially add interfaces allowing you to plugin tracking of that in other ways.

4. That is outside the scope of cloudscribe, if you need it in a custom feature you can certainly use it, nothing about cloudscribe stops you from using that. Long term I don't want to be stuck with much jquery dependencies, I'm moving away from that though we still have some dependencies and bootstrap also has some, I don't want to add more.

5. Since cloudscribe is not a framework there is no prescribed way to build things, you build things any way that you normally would build things for asp.net core. If you want to make multi-tenant aware features you should tag your custom data with siteid so you can retrieve it per tenant. See also https://www.cloudscribe.com/docs/building-custom-features-that-integrate-with-cloudscribe-core
https://www.cloudscribe.com/docs/looking-up-users-in-custom-features
https://www.cloudscribe.com/docs/adding-tables-and-data-for-custom-features

6. I am working on a marketplace to sell custom features and working on commercial features to sell. More specifically I've built a system to sell license activation as my commercial features will be available on nuget and free to try but will have some nag screens or other limitations that can be removed by getting a license. As such I don't plan to sell downloads or build infrastructure for downloads.

If community members want to share custom features I am happy to create a page to link to them if/when there are people who want to share them. One could make github repos with sample apps for custom features just as I have done with the components I've built.

7. Same answer as 5, I have no prescription for how you should build custom things and therefore nothing to offer in terms of scaffolding.

8. That is outside the scope of cloudscribe Core and cloudscribe SimpleContent. If I build ecommerce features they will be commercial add ons,

9. Already planned but won't begin work until it comes out of beta. The current bootstrap3 views are all in separate nuget packages so bootstrap4 will just be new alternative nugets

10. Updates happen by updating to the latest nuget packages,, then you have to rebuild and publish your app. I have no way to automate that.

**Comment by joeaudette** [comment]
as noted in #356 bootstrap4 is now out of beta, so work will begin on that very soon

**Comment by weedkiller** [comment]
ok thanks
