### ISSUE TITLE
Adding native objects store

### ISSUE THREAD

**Issue by papyr** [joeaudette/cloudscribe#372]
Hi @joeaudette I like your software, and I am looking to help, contribute a new object store as the backend. 

I need some information on how to configure that, so it can use linq with cloudscribe.
Can you also consider adding 1) a couple more views to manage, users in roles, and Roles that have users. 2) groups (collection of roles), so that users can be added to a group of roles. For e.g. 

- `AdminGRoup `= (SiteManager, Mgr)
- `SuperAdminGRoup `= (AdminGRoup + TenantAdmin)
-  Scaffolder to generate, cloudscribe specific objects, based on a table entity.
-  Stateless integration for workflow, for now just bring it into the solution, we can figure out the roadmap later.

Dynamic data will help us a lot [here is link](https://github.com/RolandPheasant/DynamicData)

**Comment by joeaudette** [comment]
For any significant contribution of code to the project will need a signed contributor agreement as discussed in [Contributing](https://github.com/joeaudette/cloudscribe/blob/master/CONTRIBUTING.md)

If you do that then I'm happy to answer any specific questions you may have as you implement a new storage layer. Or since data storage are separate projects and nuget packages nothing prevents you from implementing a new storage layer in your own code repository. You only need to reference the nuget for cloudscribe.Core.Models and implement the interfaces for queries and commands. For things that go into this repository I'm kind of on the hook to support them, I have no idea if you will be around to maintain a new storage layer over time so I'm not overly eager to add new storage layers here.

I'm not keen on the idea of introducing a new concept for groups, I consider roles are already groups and security policy goes by roles and claims so any group should be represented by either a role or a claim.

There is not much prescription in how to build features that work with cloudscribe, it is a set of libraries not a framework, so you can build features any way that you normally would for asp.net core. therefore there is nothing I wish to provide scaffolding for.

I have no idea what you are suggesting with your last bullet or mentioning dynamic data and see no reason to expand the scope of what is included in cloudscribe core. You have not made any pitch or case why such things should be added other than you want them. As far as I know nothing prevents you from using anything you want in your own custom code or features that you may build. Not everything needs to be baked into cloudscribe Core.
