### ISSUE TITLE
Entityframework7 repository is nice feature to have.

### ISSUE THREAD

**Issue by mikeandersun** [joeaudette/cloudscribe#4]
I saw you told about having Entity framework repository in future. But I think if it be available , it help to rapid development. I think what you care about having O/R  is performance, a developer can develop an app with Entity Framework rapidly and then implement the repository with what ever ADO repository that achieve the best performance.
Nowadays developer start a thing and end up with another thing according to competitions, so code first reduce maintenance of code at least in staring phase of a project. may I am in correct :)

**Comment by joeaudette** [comment]
yes I like Entity Framework 7 myself and understand it's benefits and the trade-offs. I would like to implement repositories using it in the future but I don't want to require anyone who uses this project to use it. 

Some people like NHibernate or other ORMs. 

The current repositories were built using existing schema and ado code from my old project mojoportal with lots of refactoring to make it async and to use more modern patterns. Some of the data fields in the sites and users tables will be removed or moved to other new tables later. I'm also trying to keep it possible for people to migrate existing sites and users from mojoportal, so I need to plan carefully about removing legacy fields. Once the schema and the models have been cleaned up of legacy fields it will be easier to begin work with EF7 repositories. 

I expect many people will want to use EF7 and that is why I want to implement repositories for it. But people can still build on top of it their own functionality using EF7 or any other ORM that supports dnxcore50 regardless of whether that is used for the current repositories.

For example I do think some people will want to use NHibernate and those people probably don't want their project to also depend on EF7. So my approach is to not impose any specific ORM, especially since I already had some good working ado code to start with.

**Comment by joeaudette** [comment]
EF7 core repositories are now fully implemented.

Note that if you use the EF7 repository implementations, then you do not need to use the /Setup system, instead you would add this at the end of the Configure method in Startup.cs of your app:

    cloudscribe.Core.Repositories.EF.InitialData.InitializeDatabaseAsync(app.ApplicationServices).Wait();

If you are also using the DbLogger with EF then you would also add:

     cloudscribe.Logging.EF.DbInitializer.InitializeDatabaseAsync(app.ApplicationServices).Wait();

One problem with using EF to log things is that if you have loglevel set to Information, Debug, or Trace, then there is a problem because Entity Framework logs a lot of things at those levels. So when you save a logitem with EF it generates more log items, basically in a continuous loop of creating log data.
To solve that we have to filter out the Entity Framework logging, but that seems like a problem because you might be interested in what is being logged by EF.

A better solution is probably to use the MSSQL logrepository which does not use EF for logging. You can still use EF for the core repositories. That way there is no need to filter out EF from logging. Hopefully soon I can get around to documenting the steps for that since the mssql logrepository depends on the setup system to run its sql script or it would need to be run manually.

Note also that this implementation for EF7 is specifically for MS SQL Server/SqlAzure. Trying to have a single generic mapping of the model is not optimal, it is recommended to do a more optimal mapping for the specific database provider. So for the core repositories I defined [ICoreModelMapper](https://github.com/joeaudette/cloudscribe/blob/master/src/cloudscribe.Core.Repositories.EF/ICoreModelMapper.cs) and [SqlServerCoreModelMapper](https://github.com/joeaudette/cloudscribe/blob/master/src/cloudscribe.Core.Repositories.EF/SqlServerCoreModelMapper.cs) using sql server specific mappings. To create a mapping for another database platform would just require implementing a new ICoreModelMapper.

**Comment by joeaudette** [comment]
After implementing EF support, I decided it would be the main data layer going forward so I can take advantage of the rapid development benefits it provides. I've update the project readme to not that the [other data layers have been moved to a separate code repository](https://github.com/joeaudette/cloudscribe.Core.Data). As such I think it is time to close this issue.
