### ISSUE TITLE
When will come the nuget package?

### ISSUE THREAD

**Issue by mikeandersun** [joeaudette/cloudscribe#43]

**Comment by joeaudette** [comment]
sometimes you open issues for things that would be better to ask on gitter

I don't know how soon I will publish nugets, I still have a lot to do and I don't think I should publish nugets prematurely before other things are ready

right now I'm working on localization for cloudscribe core. To get the behavior I want and to work around [localization bugs in rc2](https://github.com/aspnet/Localization/issues/157#issuecomment-222841152) it looks like I will need to implement a custom StringLocalizerFactory. even with the bugs fixed the localization system doesn't really do what I want. for web apps it is possible to configure a Resources folder where resx files can be dropped in to localize things. that works fine for the main web app but if my controller is in a class library then dropping in a new resx  in the folder doesn't help localizing the class library, it only works for the main web app. I want it to work also for the class library such that if my class library has embedded resx for the needed language it will use that but if not found it will look in the Resources folder for the main web app. I want it to be easy to add localization for any of the components by dropping in new resx files no matter whether the component is in a nuget class library. sort of like the old App_GlobalResources. If I can make it work like I want then it will be easy for people to author resx files for new languages and drop them in, and that will also make it easy for people to contribute those resx files back to the project so they can be shared. Since virtually all of the cloudscribe components will be in nuget/class libraries, not in the main web app, this is an important goal. otherwise it will be difficult for people to add their own languages without forking the code to add their resx files as embedded into the class library

localization seems like an important thing to have ready before shipping nugets

actually I might publish nugets for cloudscribe.SimpleContent sooner than for cloudscribe.Core, because I want to rebuild my personal blog with it and I need nugets for that project. I have many goals competing for my time which makes it hard to predict when specific things will happen. updating my personal website is a high priority goal for me because I want to start blogging more but I don't want to do that until I update my site. I may stop working on cloudscribe core for a little while soon in order to work on my site

**Comment by joeaudette** [comment]
fyi, got this done 

https://github.com/joeaudette/cloudscribe.Web.Localization

so now I can start implementing localization in cloudscribe core

**Comment by coe-jeubanks** [comment]
Nice one, Joe! Even though we didn't need it, I always admired how well-implemented the localization features are in mojoPortal, and how easily translation resource files could be used by sites around the world. I'm glad to see that cloudscribe will have the same capabilities for translation.

**Comment by joeaudette** [comment]
Thanks Jamie!
When I get further along with this project, I could look for English strings in mojoportal resx files that are the same as in cloudscribe then I can potentially harvest some of the translations from mojoportal to create translations for cloudscribe.

**Comment by joeaudette** [comment]
fyi, there are nuget packages for cloudscribe Core available if you have not noticed. I am currently working on integration for cloudscribe Core and cloudscribe SimpleContent. I did a quick and dirty single tenant integration already and updated my site joeaudette.com which is now using cloudscribe Core and Simple Content both with NoDb. But the integration is not really how I want it to be so it will be changing but at least I have one site in production as proof of concept

**Comment by mikeandersun** [comment]
thanks joe.
I 'm using those as you published.
