### ISSUE TITLE
Additional information: Failed to convert '1' to type 'System.Guid'.

### ISSUE THREAD

**Issue by ramusbucket** [joeaudette/cloudscribe#45]
I'm starting with this and getting error when I try to run example.WebApp. I get error on line - `  var multiTenantOptions = multiTenantOptionsAccessor.Value;`

**Comment by joeaudette** [comment]
thanks for letting me know, the error was caused by a bad value in appsettings.json because at one time I was using integer ids but forgot to change that when I changed to using guid ids. I just fixed it in [this change](https://github.com/joeaudette/cloudscribe/commit/75aa9abcde6f859b589e8747454933b65c91ecbd)

please let me know if updating to the latest code does not solve it for you

**Comment by joeaudette** [comment]
I'm overriding things in appsettings.local.overrides.json and my settings there were good which is why I had not noticed this issue

**Comment by microquiz** [comment]
Hi Jo.
I have been following from the side lines... What does your new project do?   I am a fan of mojo.

Ray Bevan

**Comment by joeaudette** [comment]
Hi Ray!
First let me say thanks for the beers! and for supporting my business by purchasing add ons for mojoportal. It has not gone un-noticed! I really appreciate it!

I have a number of related projects in the works, all tied together under the brand cloudscribe. This one (cloudscribe Core) is like a foundation to build other things on. All it provides is management for sites, users, roles, I've described it in the [main readme here](https://github.com/joeaudette/cloudscribe/blob/master/README.md).

I have another project [cloudscribe.SimpleContent](https://github.com/joeaudette/cloudscribe.SimpleContent/blob/master/README.md) which may also be of interest to you. At the moment there is no integration between them, ie SimpleContent does not depend on using cloudscribe Core (though it does use a few components that are part of cloudscribe Core but available as separate nugets). SimpleContent in my current examples uses [cloudscribe.SimpleAuth](https://github.com/joeaudette/cloudscribe.Web.SimpleAuth) instead of cloudscribe Core, but it is just an example, they are loosely coupled so SimpleContent does not directly depend on SimpleAuth either, and I plan soon to implement examples using cloudscribe Core and SimpleContent together.

If you'd like to discuss it further or ask casual questions about my new projects, feel free to join my gitter chat room here https://gitter.im/joeaudette/cloudscribe

Best Regards,

Joe

**Comment by ramusbucket** [comment]
Yes, Joe, that worked! thank you for taking out time to look at this issue. Do you have some tutorial where I can instruction about how to see it in action. Right now, I get normal Asp.Net mvc site where I can normally register and login/log off but I cannot seem to understand how can I exercise tenant functionality.

**Comment by joeaudette** [comment]
@ramusbucket see [this wiki page](https://github.com/joeaudette/cloudscribe/wiki/Working-with-the-source-Code)

the first site aka tenant is created automatically at the first startup and you should be able to login as admin@admin.com with password admin and when you do that administration menu should appear. The first site is considered the server admin site, admins in this site can create additional sites from the ui

**Comment by ramusbucket** [comment]
Yep, That helped. Awesome, I can see the point clearly now about Multi tenants. Thanks a lot!

**Comment by ramusbucket** [comment]
Hi Joe, sent you an email on unrelated things.
