### ISSUE TITLE
A route to render virtual pages.

### ISSUE THREAD

**Issue by mikeandersun** [joeaudette/cloudscribe#8]
I start a project to render virtual pages(e.g site/page1, site2/pag2 , /page1) I have a route to render pages in my project and add a maproute to `startup.cs`
```
routes.MapRoute(
                      name: "renderpage",
                      template: "{sitefolder}/{id?}",
                      defaults: new { controller = "RenderController", action = "RenderPage" },
                      constraints: new { name = new PageRouteConstraint() }
                      );
```
But the core routes (e.g `SiteAdmin`) refer to my route.

**Comment by joeaudette** [comment]
Understanding ASP.NET Routing:

it is very important that routes are registered in the correct order. more specific routes must be registered first and less specific routes must be registered later. a request may match more than one route.

When a request comes in it is compared to routes in the route table and the first route it matches is used no matter if a better match exists. therefore if a less specific route is registered first it will catch requests that would have a better match with a more specific route that was registered later.

ie the default route is usually the least specific route and must be registered last

something like a route for a cms would likely need to be the default route added last especially if you are not going to use a controller segment in the route because without a controller segment the route is less specific
