### ISSUE TITLE
[Question] Extending the data layer

### ISSUE THREAD

**Issue by dazinator** [joeaudette/cloudscribe#87]
Hi Joe, very interesting repository, thanks for sharing.

I am developing an extensible CMS, where "modules" can be installed, and this has me wondering about how to best handle module authors wanting to "extend" core tables.

For example, suppose there was a module that wanted to add a column to your SiteHost table. What would the recommended method be? Ofcourse, the module developer could bypass EF all together and manually add the column using ADO,NET and use ADO.NET for future data access - but what if they added a mandatory column? It could break the existing CoreDbContext which wouldn't be aware of the model changes.

The only real solution i can think for this is that you just stipulate that the core tables are not extensible, and the core model is not extensible, and that if you want extend them, you'd have to create your own EF model / DbContext, and "join" to the appropriate core tables rather than extend them. But again this raised problems because let's say a module author creates a table that "joins" to the SiteHost table. Now if the core DBContext ever tries to delete that record, it will hit a foreign key violation.

This basically leads to the idea that:

1. You shouldn't allow module developers to extend core tables.
2. You shouldn't allow module developers to place new constraints (like foreign keys) on core table's.

This is generally bad for database design, as being able to extend tables and introduce new constraints where needed helps keep the integrity of data. Forcing people to drop that doesn't sound right.

Just wondering if you have thought about this kind of stuff or if it's not really a concern for you at the moment.

**Comment by joeaudette** [comment]
my position is that the core models and tables should not be extended, any custom data that you need to store should be in your own tables and you should not introduce any foreign keys onto the core tables. 

you can store keys such as SiteId, UserId etc in your own tables to associate custom data but such columns should not be foreign keys, they can be indexed, they can have have unique constraints if needed but they should not be foreign keys. foreign keys are overrated and over used in my opinion, they are specific to relational models. since I am supporting other forms of data storage not just relational I don't want to impose relational concepts in my models.  There are a lot of advantages to letting go of old strict relational ideas, that is why the NoSql movement has happened. Even if I am supporting relational storage doesn't mean I have to embrace all the relational paradigms. 

I cannot prevent people from doing things against my advice. People are free to do whatever they want and also free to accept any consequences of what they do. If people choose to do things I don't recommend then it is not my responsibility to shelter them from the good or bad outcome of their decisions.

**Comment by dazinator** [comment]
Thanks Joe, that makes sense, and that's basically saying that to avoid problems like those mentioned, the Core Data Model is fixed, and not extensible. That works for sure. I still think though that there are valid scenarios when it's more desirable for an extension to the system to add a column to an existing table, or add a foreign key referencing an existing table, rather than creating a new table, or attempting to link to existing records without a FK relationship to ensure integrity.. I am hoping that it is just a matter of figuring out what the rules are to enable that to happen in a way that will not break existing DbContexts.. Still easier to avoid this problem than attempt to address it if possible.. In the meantime I have raised something over at EF, will be interesting to see if I get anymore feedback! https://github.com/aspnet/EntityFramework/issues/6961
