### ISSUE TITLE
Move Datalayer projects to separated Nuget packages.

### ISSUE THREAD

**Issue by mikeandersun** [joeaudette/cloudscribe#9]
It is possible to move data layer projects to separated projects that come in via Nuget packages?

**Comment by joeaudette** [comment]
The plan is for everything to be published as nuget packages but things are not ready for that yet.

The goal is is that people will be able to start with an empty web app project and pull in all of the cloudscribe components via nuget and the resulting web app will have all the functionality you see currently in the webhost app. Then they can add their own code for controllers and views to build whatever they want.

So when you look at the cloudscribe solution today you should think of every project in the solution will be a nuget package except the webhost project which represents the user's own project and what it should have after pulling in the nugets.

The thing that is holding us back from publishing everything as nuget packages is because nuget cannot yet install file contents into the web app. For example when a webapp takes a nuget dependency on cloudscribe.Core.Web we will need to install views (.cshtml files). Similarly the data projects need to be able to install sql scripts in the config folder within the webapp so the setup page can run it. We will also need a way to provide the integration code for startup but that code can be modified after it is installed.

As of beta8 tooling, it is now possible to package those needed content files into the nuget package that is created by VS 2015 when building a project. But that is only half way there, currently nuget does not install the files into the webapp, it just ignores them. So we have to wait until all the pieces are ready including work happening in the .net framework as well as work that is happening with VS 2015 tooling and nuget before we can publish nuget packages that do what we need them to do.

We are still in very early stages and we are blocked from doing some things we plan to do while we wait for other pieces to fall into place.
